"Filed out from Dolphin Smalltalk X6"!

Smalltalk at: #_BehaviorMasks put: (PoolConstantsDictionary named: #_BehaviorMasks)!
_BehaviorMasks at: '_BasicSpecMask' put: 16r7FFF!
_BehaviorMasks at: '_BytesSubMask' put: 16r4800!
_BehaviorMasks at: '_FundamentalShapeMask' put: 16r30FF!
_BehaviorMasks at: '_IndirectMask' put: 16r800!
_BehaviorMasks at: '_MournerMask' put: 16r400!
_BehaviorMasks at: '_NullTermMask' put: 16r4000!
_BehaviorMasks at: '_PointersMask' put: 16r2000!
_BehaviorMasks at: '_ShapeMask' put: 16r70FF!
_BehaviorMasks at: '_SizeMask' put: 16rFF!
_BehaviorMasks at: '_VariableMask' put: 16r1000!
_BehaviorMasks shrink!
