"Filed out from Dolphin Smalltalk 7"!

Notification subclass: #CommandLineError
	instanceVariableNames: ''
	classVariableNames: ''
	imports: #()
	classInstanceVariableNames: ''
	classConstants: {}!
CommandLineError guid: (GUID fromString: '{d61804f9-bdca-4575-b3e9-79404d529a8b}')!
CommandLineError comment: 'For now unexpected options, ambiguous options, and missing arguments are provided to the application as a Notification.'!
!CommandLineError categoriesForClass!Kernel-Exception Handling! !
