"Filed out from Dolphin Smalltalk 7"!

Kernel.Namespace subclass: #Core
	instanceVariableNames: ''
	classVariableNames: ''
	imports: #(#{Kernel private})
	classInstanceVariableNames: ''
	classConstants: {}!
Core guid: (Core.GUID fromString: '{0580d7be-e00d-41c8-84a1-910e03a0babd}')!
Core isNonInstantiable: true!
Core comment: 'Namespace of the core Smalltalk class hierarchy.'!
!Core categoriesForClass!Kernel-Objects! !
