"Filed out from Dolphin Smalltalk 7"!

AbstractDictionaryTest subclass: #LookupTableTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''
	classConstants: {}!
LookupTableTest guid: (GUID fromString: '{5c366850-2830-493e-a387-2a621f4bc8b2}')!
LookupTableTest comment: ''!
!LookupTableTest categoriesForClass!Unclassified! !
!LookupTableTest methodsFor!

collectionClass
	^LookupTable! !
!LookupTableTest categoriesFor: #collectionClass!helpers!private! !

