"Filed out from Dolphin Smalltalk 7"!

ExternalArrayTest subclass: #DOUBLEArrayTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''
	classConstants: {}!
DOUBLEArrayTest guid: (GUID fromString: '{d4fa7f6e-7be8-407b-a002-47d609d8d311}')!
DOUBLEArrayTest comment: ''!
!DOUBLEArrayTest categoriesForClass!Unclassified! !
!DOUBLEArrayTest methodsFor!

arrayClass
	^DOUBLEArray!

elementFromValue: anObject 
	^anObject asFloat! !
!DOUBLEArrayTest categoriesFor: #arrayClass!constants!private! !
!DOUBLEArrayTest categoriesFor: #elementFromValue:!private!unit tests! !

