"Filed out from Dolphin Smalltalk 7"!

SortAlgorithmTest subclass: #HeapsortAlgorithmTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''
	classConstants: {}!
HeapsortAlgorithmTest guid: (GUID fromString: '{7d774650-ec2f-46fa-acae-1f6c9a99ab42}')!
HeapsortAlgorithmTest comment: ''!
!HeapsortAlgorithmTest categoriesForClass!Unclassified! !
!HeapsortAlgorithmTest methodsFor!

algorithmToTest
	^HeapsortAlgorithm! !
!HeapsortAlgorithmTest categoriesFor: #algorithmToTest!private!unit tests! !

