"Filed out from Dolphin Smalltalk 7"!

LookupTableTest subclass: #IdentityDictionaryTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''
	classConstants: {}!
IdentityDictionaryTest guid: (GUID fromString: '{89184496-00fe-46a7-a9d7-2e531f4b088c}')!
IdentityDictionaryTest comment: ''!
!IdentityDictionaryTest categoriesForClass!Unclassified! !
!IdentityDictionaryTest methodsFor!

collectionClass
	^IdentityDictionary! !
!IdentityDictionaryTest categoriesFor: #collectionClass!helpers!private! !

