"Filed out from Dolphin Smalltalk 7"!

Kernel subclass: #'Kernel.Tests'
	instanceVariableNames: ''
	classVariableNames: ''
	imports: #(#{XProgramming.SUnit})
	classInstanceVariableNames: ''
	classConstants: {}!
Kernel.Tests guid: (Core.GUID fromString: '{d6553f2a-1910-4d74-b00a-3406f34b8709}')!
Kernel.Tests isNonInstantiable: true!
Kernel.Tests comment: ''!
!Kernel.Tests categoriesForClass!Kernel-Objects! !
!Kernel.Tests class methodsFor!

icon
	"Answers an Icon that can be used to represent this class, the emoji 🧪"

	^TestCase icon! !
!Kernel.Tests class categoriesFor: #icon!constants!public! !

