"Filed out from Dolphin Smalltalk 7"!

MultiByteStringTest subclass: #Utf8StringTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Utf8StringTest guid: (GUID fromString: '{cc364a8d-e3ae-493e-8856-3f10c847c10d}')!
Utf8StringTest comment: ''!
!Utf8StringTest categoriesForClass!Unclassified! !
!Utf8StringTest methodsFor!

assimilateString: aString
	^aString asUtf8String!

collectionClass
	^Utf8String! !
!Utf8StringTest categoriesFor: #assimilateString:!helpers!private! !
!Utf8StringTest categoriesFor: #collectionClass!helpers!private! !

