"Filed out from Dolphin Smalltalk 7"!

ClassBrowserAbstractTest subclass: #ClassBrowserTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''
	classConstants: {}!
ClassBrowserTest guid: (GUID fromString: '{4b7ae148-8981-49e2-9ad0-0f0aac6f1172}')!
ClassBrowserTest comment: ''!
!ClassBrowserTest categoriesForClass!Unclassified! !
!ClassBrowserTest methodsFor!

browserClass
	^ClassBrowserShell! !
!ClassBrowserTest categoriesFor: #browserClass!public!Running! !

