"Filed out from Dolphin Smalltalk 7"!

ClassBrowserAbstractTest subclass: #SystemBrowserTest
	instanceVariableNames: ''
	classVariableNames: ''
	imports: #()
	classInstanceVariableNames: ''
	classConstants: {}!
SystemBrowserTest guid: (Core.GUID fromString: '{2e020526-2bd1-4fb6-b539-9c2456468a2c}')!
SystemBrowserTest comment: ''!
!SystemBrowserTest categoriesForClass!Unclassified! !
!SystemBrowserTest methodsFor!

browserClass
	^SystemBrowserShell! !
!SystemBrowserTest categoriesFor: #browserClass!public!Running! !

