"Filed out from Dolphin Smalltalk"!

STON
	subclass: #'STON.Tests'
	instanceVariableNames: ''
	classVariableNames: ''
	imports: #(#{Graphics} #{XProgramming.SUnit})
	classInstanceVariableNames: ''
	classConstants: {}!

STON.Tests guid: (Core.GUID fromString: '{cb2bee4b-3c19-4122-9d13-e039d98ed8d2}')!

STON.Tests isNonInstantiable: true!

STON.Tests comment: ''!

!STON.Tests categoriesForClass!Kernel-Objects! !

!STON.Tests class methodsFor!

icon
	"Answers an Icon that can be used to represent this class, the emoji 🧪"

	^TestCase icon! !

!STON.Tests class categoriesForMethods!
icon!constants!public! !
!

