@echo off
rem -- Get git tag and commit information for use in product version

rem -- this seems to be the way to get the result of a command into a variable
for /f %%i in ('git describe --tag') do set GIT_TAG=%%i

rem -- generate Version.h in the intermediate directory (passed in as first argument)

echo // this file generated by getVersion.cmd on %date% at %time% > %1Version.h
echo #if defined(_DEBUG) >> %1Version.h
echo #define GIT_TAG "%GIT_TAG% (Debug)" >> %1Version.h
echo #else >> %1Version.h
echo #define GIT_TAG "%GIT_TAG%" >> %1Version.h
echo #endif >> %1Version.h