///////////////////////////////////////////////////////////////////////////////
// Structure exception codes

#pragma once
#include <winerror.h>
#include "rc_vm.h"

// Similar to MAKE_SCODE, but makes a customer (non-MS) exception code
#define MAKE_CUST_SCODE(sev,fac,code) (DWORD((1<<29) | MAKE_SCODE(sev, fac, code)))

// Define the exception code to jump out of Smalltalk back to caller
#define SE_VMCALLBACKEXIT	MAKE_CUST_SCODE(SEVERITY_SUCCESS, FACILITY_NULL, 0)
#define SE_VMCALLBACKUNWIND	MAKE_CUST_SCODE(SEVERITY_SUCCESS, FACILITY_NULL, 1)
// This is handy for forcing crash dump output when one doesn't want an actual crash
// (useful during debugging for recording machine state, for example).
#define SE_VMDUMPSTATUS		MAKE_CUST_SCODE(SEVERITY_SUCCESS, FACILITY_NULL, 2)

#define SE_VMCRTFAULT		MAKE_CUST_SCODE(SEVERITY_ERROR, FACILITY_NULL, IDP_CRTFAULT)
#define SE_VMRECURSIVEDNU	MAKE_CUST_SCODE(SEVERITY_ERROR, FACILITY_NULL, IDP_RECURSIVEDNU)
#define SE_VMSTACKOVERFLOW	MAKE_CUST_SCODE(SEVERITY_ERROR, FACILITY_NULL, IDP_STACKOVERFLOW)
#define SE_VMOTFULL			MAKE_CUST_SCODE(SEVERITY_ERROR, FACILITY_NULL, IDP_OTFULL)
#define SE_VMOTCOMMITFAIL	MAKE_CUST_SCODE(SEVERITY_ERROR, FACILITY_NULL, IDP_OTCOMMITFAIL)
#define SE_VMEXIT			MAKE_CUST_SCODE(SEVERITY_ERROR, FACILITY_NULL, IDP_EXIT)
#define SE_VMOTRESERVEFAIL	MAKE_CUST_SCODE(SEVERITY_ERROR, FACILITY_NULL, IDP_OTRESERVEFAIL)
#define SE_VMZCTRESERVEFAIL MAKE_CUST_SCODE(SEVERITY_ERROR, FACILITY_NULL, IDP_ZCTRESERVEFAIL)
#define SE_VMZCTCOMMITFAIL	MAKE_CUST_SCODE(SEVERITY_ERROR, FACILITY_NULL, IDP_ZCTCOMMITFAIL)
#define SE_VMFIRST			SE_VMCRTFAULT
#define SE_VMLAST			SE_VMZCTCOMMITFAIL

