"Filed out from Dolphin Smalltalk"!

OS.COM.Tests.CountedArrayTest
	subclass: #'OS.COM.Tests.CAUHTest'
	instanceVariableNames: ''
	classVariableNames: ''
	imports: #()
	classInstanceVariableNames: ''
	classConstants: {}!

OS.COM.Tests.CAUHTest guid: (Core.GUID fromString: '{835b9e74-32ad-4cc3-9543-422810c171d3}')!

OS.COM.Tests.CAUHTest comment: ''!

!OS.COM.Tests.CAUHTest class methodsFor!

arrayClass
	^CAUH!

externalArrayTestClass
	^External.Tests.UInt64ArrayTest! !

!OS.COM.Tests.CAUHTest class categoriesForMethods!
arrayClass!constants!private! !
externalArrayTestClass!constants!private! !
!

