"Filed out from Dolphin Smalltalk"!

Kernel.Namespace
	subclass: #Security
	instanceVariableNames: ''
	classVariableNames: ''
	imports: #(#{Core} #{Kernel private})
	classInstanceVariableNames: ''
	classConstants: {}!

Security guid: (Core.GUID fromString: '{a4d7c4a0-8375-473b-ab88-935baa66db4b}')!

Security isNonInstantiable: true!

Security comment: ''!

!Security categoriesForClass!Kernel-Objects! !

