"Filed out from Dolphin Smalltalk"!

Kernel.Parser
	subclass: #'Refactory.Browser.RBParser'
	instanceVariableNames: ''
	classVariableNames: ''
	imports: #()
	classInstanceVariableNames: ''
	classConstants: {}!

Refactory.Browser.RBParser guid: (Core.GUID fromString: '{886643ae-75b7-493e-a988-4d05126484ff}')!

Refactory.Browser.RBParser comment: ''!

!Refactory.Browser.RBParser categoriesForClass!System-Compiler! !

!Refactory.Browser.RBParser methodsFor!

qualifiedReferenceNodeClass
	^RBQualifiedReferenceNode! !

!Refactory.Browser.RBParser categoriesForMethods!
qualifiedReferenceNodeClass!constants!private! !
!

