"Filed out from Dolphin Smalltalk"!

Kernel.Tests.StValueTokenTest
	subclass: #'Kernel.Tests.StLiteralArrayTokenTest'
	instanceVariableNames: ''
	classVariableNames: ''
	imports: #()
	classInstanceVariableNames: ''
	classConstants: {}!
Kernel.Tests.StLiteralArrayTokenTest guid: (Core.GUID fromString: '{dff6e9a2-a766-4469-b3d1-0b7b1fa8d1dc}')!
Kernel.Tests.StLiteralArrayTokenTest comment: ''!
!Kernel.Tests.StLiteralArrayTokenTest methodsFor!

exampleSource
	^'#('!

subjectClass
	^StLiteralArrayToken! !
!Kernel.Tests.StLiteralArrayTokenTest categoriesForMethods!
exampleSource!constants!private! !
subjectClass!constants!private! !
!

