"Filed out from Dolphin Smalltalk"!

StValueTokenTest subclass: #StSpecialCharacterTokenTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
StSpecialCharacterTokenTest guid: (GUID fromString: '{adf66b34-f041-4d5f-bb4f-0843ea9096eb}')!
StSpecialCharacterTokenTest comment: ''!
!StSpecialCharacterTokenTest categoriesForClass!Unclassified! !
!StSpecialCharacterTokenTest methodsFor!

exampleSource
	^':'!

exampleValue
	^$:!

subjectClass
	^StSpecialCharacterToken! !
!StSpecialCharacterTokenTest categoriesForMethods!
exampleSource!constants!private! !
exampleValue!constants!private! !
subjectClass!constants!private! !
!

