"Filed out from Dolphin Smalltalk"!

Kernel.StStaticVariable
	subclass: #'Kernel.StWorkspaceVariable'
	instanceVariableNames: ''
	classVariableNames: ''
	imports: #()
	classInstanceVariableNames: ''
	classConstants: {}!

Kernel.StWorkspaceVariable guid: (Core.GUID fromString: '{10ce1693-8cc3-40a5-a932-7030bf1a85c0}')!

Kernel.StWorkspaceVariable comment: ''!

!Kernel.StWorkspaceVariable categoriesForClass!Kernel-Objects! !

