"Filed out from Dolphin Smalltalk 7"!

Kernel.SharedPool subclass: #'OS.COM.StructuredStorageConstants'
	instanceVariableNames: ''
	classVariableNames: ''
	imports: #()
	classInstanceVariableNames: ''
	classConstants: {
		'LOCK_EXCLUSIVE' -> 16r2.
		'LOCK_ONLYONCE' -> 16r4.
		'LOCK_WRITE' -> 16r1.
		'STATFLAG_DEFAULT' -> 16r0.
		'STATFLAG_NONAME' -> 16r1.
		'STATFLAG_NOOPEN' -> 16r2.
		'STG_E_ACCESSDENIED' -> -16r7FFCFFFB.
		'STG_E_INVALIDFUNCTION' -> -16r7FFCFFFF.
		'STGC_DANGEROUSLYCOMMITMERELYTODISKCACHE' -> 16r4.
		'STGC_DEFAULT' -> 16r0.
		'STGC_ONLYIFCURRENT' -> 16r2.
		'STGC_OVERWRITE' -> 16r1.
		'STGFMT_CATALOG' -> 16r2.
		'STGFMT_DIRECTORY' -> 16r1.
		'STGFMT_DOCUMENT' -> 16r0.
		'STGFMT_FILE' -> 16r3.
		'STGM_CONVERT' -> 16r20000.
		'STGM_CREATE' -> 16r1000.
		'STGM_DELETEONRELEASE' -> 16r4000000.
		'STGM_DIRECT' -> 16r0.
		'STGM_FAILIFTHERE' -> 16r0.
		'STGM_NOSCRATCH' -> 16r100000.
		'STGM_NOSNAPSHOT' -> 16r200000.
		'STGM_PRIORITY' -> 16r40000.
		'STGM_READ' -> 16r0.
		'STGM_READWRITE' -> 16r2.
		'STGM_SHARE_DENY_NONE' -> 16r40.
		'STGM_SHARE_DENY_READ' -> 16r30.
		'STGM_SHARE_DENY_WRITE' -> 16r20.
		'STGM_SHARE_EXCLUSIVE' -> 16r10.
		'STGM_SIMPLE' -> 16r8000000.
		'STGM_TRANSACTED' -> 16r10000.
		'STGM_WRITE' -> 16r1.
		'STGMOVE_COPY' -> 16r1.
		'STGMOVE_MOVE' -> 16r0.
		'STGMOVE_SHALLOWCOPY' -> 16r2.
		'STGTY_LOCKBYTES' -> 16r3.
		'STGTY_PROPERTY' -> 16r4.
		'STGTY_STORAGE' -> 16r1.
		'STGTY_STREAM' -> 16r2.
		'STREAM_SEEK_CUR' -> 16r1.
		'STREAM_SEEK_END' -> 16r2.
		'STREAM_SEEK_SET' -> 16r0
	}!
OS.COM.StructuredStorageConstants guid: (Core.GUID fromString: '{3ed0417a-f038-403d-abb9-4bf66a49a04d}')!
OS.COM.StructuredStorageConstants isNonInstantiable: true!
OS.COM.StructuredStorageConstants comment: ''!
!OS.COM.StructuredStorageConstants categoriesForClass!Unclassified! !
