"Filed out from Dolphin Smalltalk 7"!

#{ProgressBarConstants} declare: (PoolConstantsDictionary named: #ProgressBarConstants)!
ProgressBarConstants at: 'PBM_DELTAPOS' put: 16r403!
ProgressBarConstants at: 'PBM_GETPOS' put: 16r408!
ProgressBarConstants at: 'PBM_GETRANGE' put: 16r407!
ProgressBarConstants at: 'PBM_SETBARCOLOR' put: 16r409!
ProgressBarConstants at: 'PBM_SETBKCOLOR' put: 16r2001!
ProgressBarConstants at: 'PBM_SETMARQUEE' put: 16r40A!
ProgressBarConstants at: 'PBM_SETPOS' put: 16r402!
ProgressBarConstants at: 'PBM_SETRANGE' put: 16r401!
ProgressBarConstants at: 'PBM_SETRANGE32' put: 16r406!
ProgressBarConstants at: 'PBM_SETSTEP' put: 16r404!
ProgressBarConstants at: 'PBM_STEPIT' put: 16r405!
ProgressBarConstants at: 'PBS_MARQUEE' put: 16r8!
ProgressBarConstants at: 'PBS_SMOOTH' put: 16r1!
ProgressBarConstants at: 'PBS_VERTICAL' put: 16r4!
ProgressBarConstants shrink!
