"Filed out from Dolphin Smalltalk"!

MultipleSelectionListBoxTest subclass: #MultipleSelectionListViewTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

MultipleSelectionListViewTest guid: (GUID fromString: '{7aa66114-24d4-4bf5-86dd-3d21baf4f55c}')!

MultipleSelectionListViewTest comment: 'Test that the behaviour of the deprecated MultipleSelectionListView class retains its legacy features in the refactored ListControlView hierarchy.'!

!MultipleSelectionListViewTest categoriesForClass!Unclassified! !

!MultipleSelectionListViewTest methodsFor!

classToTest
	^MultipleSelectionListView! !

!MultipleSelectionListViewTest categoriesForMethods!
classToTest!constants!private! !
!

