"Filed out from Dolphin Smalltalk 7"!

UI.Tests.SelectableTreeItemsTest subclass: #'UI.Tests.MoenTreeViewTest2'
	instanceVariableNames: ''
	classVariableNames: ''
	imports: #()
	classInstanceVariableNames: ''
	classConstants: {}!
UI.Tests.MoenTreeViewTest2 guid: (Core.GUID fromString: '{fe4b1b34-22de-4a95-8ba2-05b2f076c51e}')!
UI.Tests.MoenTreeViewTest2 comment: 'SUnitBrowser openOnTestCase: self'!
!UI.Tests.MoenTreeViewTest2 categoriesForClass!Unclassified! !
!UI.Tests.MoenTreeViewTest2 methodsFor!

classToTest
	^MoenTreeView! !
!UI.Tests.MoenTreeViewTest2 categoriesFor: #classToTest!helpers!private! !

