"Filed out from Dolphin Smalltalk"!

SelectorEnvironment subclass: #ParseTreeEnvironment
	instanceVariableNames: 'matcher'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ParseTreeEnvironment guid: (GUID fromString: '{11ad1e72-3575-4044-93b9-434fe1185a07}')!
ParseTreeEnvironment comment: ''!
!ParseTreeEnvironment categoriesForClass!Refactory-Lint! !
!ParseTreeEnvironment methodsFor!

matcher: aParseTreeSearcher
	matcher := aParseTreeSearcher! !
!ParseTreeEnvironment categoriesForMethods!
matcher:!initialize/release!public! !
!

