"Filed out from Dolphin Smalltalk 7"!

Core.Error subclass: #'Tools.InvalidInstallationError'
	instanceVariableNames: ''
	classVariableNames: ''
	imports: #()
	classInstanceVariableNames: ''
	classConstants: {}!
Tools.InvalidInstallationError guid: (Core.GUID fromString: '{089355c5-e178-4599-a5b0-18d7bebd8acf}')!
Tools.InvalidInstallationError comment: ''!
!Tools.InvalidInstallationError categoriesForClass!Kernel-Exception Handling! !
!Tools.InvalidInstallationError methodsFor!

_descriptionFormat
	"Answer the Win32 format String to be used to format the description for the receiver."

	^'This copy of Dolphin Smalltalk has not been installed correctly; please re-install from the original source medium.'
! !
!Tools.InvalidInstallationError categoriesFor: #_descriptionFormat!displaying!public! !

