"Filed out from Dolphin Smalltalk 7"!

Object subclass: #HttpCookie
	instanceVariableNames: 'name path value'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
HttpCookie guid: (GUID fromString: '{513813e2-3c52-4758-82a1-2532bb6d6319}')!
HttpCookie comment: ''!
!HttpCookie categoriesForClass!Unclassified! !
!HttpCookie methodsFor!

name
	^name!

name: aString 
	name := aString!

path
	^path!

path: aString 
	path := aString!

value
	^value!

value: aString 
	value := aString! !
!HttpCookie categoriesFor: #name!public! !
!HttpCookie categoriesFor: #name:!public! !
!HttpCookie categoriesFor: #path!public! !
!HttpCookie categoriesFor: #path:!public! !
!HttpCookie categoriesFor: #value!public! !
!HttpCookie categoriesFor: #value:!public! !

