"Filed out from Dolphin Smalltalk X6.2"!

ODBDeserializers subclass: #ODBExternalReference
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ODBExternalReference guid: (GUID fromString: '{8162EDD9-0FB8-11D4-B091-000000000000}')!
ODBExternalReference comment: ''!
!ODBExternalReference categoriesForClass!No category! !
!ODBExternalReference class methodsFor!

odbDeserialize: deserializer 
	^deserializer loadReference! !
!ODBExternalReference class categoriesFor: #odbDeserialize:!public! !

