"Filed out from Dolphin Smalltalk 7"!

ClassBuilderTestClass subclass: #ClassBuilderTestSubClass2
	instanceVariableNames: 'var3 var4'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ClassBuilderTestSubClass2 guid: (GUID fromString: '{03783E1E-0B16-4C83-A435-BA730610ABC3}')!
ClassBuilderTestSubClass2 comment: ''!
!ClassBuilderTestSubClass2 categoriesForClass!Unclassified! !
!ClassBuilderTestSubClass2 methodsFor!

var3 ^var3!

var3: x var3 := x!

var4 ^var4!

var4: x var4 := x! !
!ClassBuilderTestSubClass2 categoriesFor: #var3!public! !
!ClassBuilderTestSubClass2 categoriesFor: #var3:!public! !
!ClassBuilderTestSubClass2 categoriesFor: #var4!public! !
!ClassBuilderTestSubClass2 categoriesFor: #var4:!public! !

