"Filed out from Dolphin Smalltalk XP"!

DhbMinimizingPoint subclass: #DhbMaximizingPoint
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
DhbMaximizingPoint guid: (GUID fromString: '{E550026D-7D2B-11D6-B6CC-00022D5019C8}')!
DhbMaximizingPoint comment: ''!
!DhbMaximizingPoint categoriesForClass!DHB Numerical! !
!DhbMaximizingPoint methodsFor!

betterThan: anOptimizingPoint
		"(c) Copyrights Didier BESSET, 2000, all rights reserved.
		 Initial code: 04-Jan-00 "
	^value > anOptimizingPoint value! !
!DhbMaximizingPoint categoriesFor: #betterThan:!information!public! !

