"Filed out from Dolphin Smalltalk"!

MainTestCase subclass: #BagFactoryANSITest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
BagFactoryANSITest guid: (GUID fromString: '{6ac712b4-66ac-454e-b274-1195e33c664e}')!
BagFactoryANSITest comment: ''!
!BagFactoryANSITest categoriesForClass!Unclassified! !
!BagFactoryANSITest methodsFor!

canonicalObject
	^Bag!

protocol
	^#'Bag factory'!

testXnew
	" <Bag factory>#new "
	#'Collection'.!

testXnewX
	" <Bag factory>#new: "
	#'Collection'.!

testXwithAllX
	" <Bag factory>#withAll: "
	#'Collection'.!

testXwithX
	" <Bag factory>#with: "
	#'Collection'.!

testXwithXwithX
	" <Bag factory>#with:with: "
	#'Collection'.!

testXwithXwithXwithX
	" <Bag factory>#with:with:with: "
	#'Collection'.!

testXwithXwithXwithXwithX
	" <Bag factory>#with:with:with:with: "
	#'Collection'.! !
!BagFactoryANSITest categoriesForMethods!
canonicalObject!public! !
protocol!public! !
testXnew!public! !
testXnewX!public! !
testXwithAllX!public! !
testXwithX!public! !
testXwithXwithX!public! !
testXwithXwithXwithX!public! !
testXwithXwithXwithXwithX!public! !
!

