"Filed out from Dolphin Smalltalk 7"!

MainTestCase subclass: #SelectorANSITest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''
	classConstants: {}!
SelectorANSITest guid: (GUID fromString: '{d5ea3520-ffb7-47ed-8536-450548213149}')!
SelectorANSITest comment: ''!
!SelectorANSITest categoriesForClass!Unclassified! !
!SelectorANSITest methodsFor!

canonicalObject
	^#isNil!

protocol
	^#'selector'! !
!SelectorANSITest categoriesFor: #canonicalObject!public! !
!SelectorANSITest categoriesFor: #protocol!public! !

