"Filed out from Dolphin Smalltalk"!

OS.Tests.TVITEMWTest
	subclass: #'OS.Tests.TVITEMEXWTest'
	instanceVariableNames: ''
	classVariableNames: ''
	imports: #()
	classInstanceVariableNames: ''
	classConstants: {}!
OS.Tests.TVITEMEXWTest guid: (Core.GUID fromString: '{c12bfa01-a016-4c72-aeaf-eaa07a97b2a6}')!
OS.Tests.TVITEMEXWTest comment: ''!
!OS.Tests.TVITEMEXWTest methodsFor!

subjectClass
	^TVITEMEXW! !
!OS.Tests.TVITEMEXWTest categoriesForMethods!
subjectClass!constants!public! !
!

