"Filed out from Dolphin Smalltalk"!

OS.Tests.NMGETINFOTIPTest
	subclass: #'OS.Tests.NMLVGETINFOTIPWTest'
	instanceVariableNames: ''
	classVariableNames: ''
	imports: #()
	classInstanceVariableNames: ''
	classConstants: {}!

OS.Tests.NMLVGETINFOTIPWTest guid: (Core.GUID fromString: '{22b3f82d-2b44-4db0-b697-235484b742d3}')!

OS.Tests.NMLVGETINFOTIPWTest comment: ''!

!OS.Tests.NMLVGETINFOTIPWTest methodsFor!

subjectClass
	^NMLVGETINFOTIPW! !

!OS.Tests.NMLVGETINFOTIPWTest categoriesForMethods!
subjectClass!constants!public! !
!

