"Filed out from Dolphin Smalltalk 7"!

Kernel.SharedPool subclass: #OLEConstants
	instanceVariableNames: ''
	classVariableNames: ''
	imports: #()
	classInstanceVariableNames: ''
	classConstants: {
		'CLSCTX_INPROC_HANDLER' -> 16r2.
		'CLSCTX_INPROC_SERVER' -> 16r1.
		'CLSCTX_LOCAL_SERVER' -> 16r4.
		'CLSCTX_REMOTE_SERVER' -> 16r10.
		'MEMCTX_SHARED' -> 16r2.
		'MEMCTX_TASK' -> 16r1.
		'REGCLS_MULTI_SEPARATE' -> 16r2.
		'REGCLS_MULTIPLEUSE' -> 16r1
	}!
OLEConstants guid: (Core.GUID fromString: '{b8d7a4c0-475a-4a59-abad-fd589aef1b2f}')!
OLEConstants isNonInstantiable: true!
OLEConstants comment: ''!
!OLEConstants categoriesForClass!Unclassified! !
