"Filed out from Dolphin Smalltalk"!

Core.Tests.DolphinTest
	subclass: #'External.Tests.IntegerBytesTest'
	instanceVariableNames: ''
	classVariableNames: ''
	imports: #()
	classInstanceVariableNames: ''
	classConstants: {}!
External.Tests.IntegerBytesTest guid: (Core.GUID fromString: '{d2ec9130-5bc5-4da7-8856-735f904ab458}')!
External.Tests.IntegerBytesTest isNonInstantiable: true!
External.Tests.IntegerBytesTest comment: ''!
