"Filed out from Dolphin Smalltalk 7"!

Announcement subclass: #AnnouncementMockB
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
AnnouncementMockB guid: (GUID fromString: '{657EF76C-42AE-4E58-82AE-6D8EF8C0FC9B}')!
AnnouncementMockB comment: 'This is a simple test mock'!
!AnnouncementMockB categoriesForClass!Announcements-Tests-Core-Mocks! !
