"Filed out from Dolphin Smalltalk 7"!

Announcement subclass: #AnnouncementMockA
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''
	classConstants: {}!
AnnouncementMockA guid: (GUID fromString: '{53387dd4-90b1-44c7-bc41-2168c30504e6}')!
AnnouncementMockA comment: 'This is a simple test mock.'!
!AnnouncementMockA categoriesForClass!Announcements-Tests-Core-Mocks! !
